#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 The MCUHome Contributors
# SPDX-License-Identifier: Apache-2.0
"""Build MCUHome's two build-environment packages — the same bytes every time.

The build environment specification
(``docs/spec/build-environment-specification.md``, generation 3) defines a
build environment as a *package set* rather than as an image, and
``docs/design/build-environment.md`` names MCUHome's set:

``mcuhome-build-workspace``
    Architecture-neutral. The materialized west workspace at the revisions
    ``west.yml`` pins, with ``patches/`` applied, the Espressif HAL blobs
    fetched, the west configuration pre-populated, the record of what was
    resolved, the pre-generated Matter data-model code, and the
    environment's self-description (specification §5).

``mcuhome-build-tools_<os>-<arch>``
    One per platform. Zephyr SDK toolchain, CMake, Ninja, gn, the complete
    wheel set the build virtual environment is created from, and the entry
    point.

One script for both kinds, because the half that must not drift is shared:
the deterministic archive writer, the file names, the sidecars and the
index. Two scripts would be two implementations of one byte-level contract.

Each package is published with its **meta file** — ``meta.json`` at the top
of the archive and ``<archive>.meta.json`` beside it, the same bytes twice.
It is the only document that travels beside an archive besides the
``.sha256``.
It states what the package is, which version of the next stage it requires
(the workspace requires tools; the tools require nothing), the hash of its
own inputs, and what it resolved to: the west projects and patches for the
workspace, the tool versions for the tools. The versions themselves come
from ``packaging/build-environment/environment.json`` at the packaged
commit — the workspace and the tools are release lines of their own, and
neither takes the SDK's version.

**Why the bytes have to be reproducible.** A build context pins packages by
hash, and every delivery of a package set — an image above all — states a
hash for every member (specification §5.1). Two parties building the same
revision must therefore reach the same digest, or the second one's package
can never satisfy a pin the first one resolved. Everything below that looks
fussy is that requirement, and it is the approach ``scripts/build_sdk_archive.py``
already uses for the SDK package: PAX format, members sorted by name, one
mtime for the whole archive, ``uid``/``gid`` 0 with empty
``uname``/``gname``, modes narrowed to two values, one fixed zstd level,
single-threaded compression.

Two differences to the SDK archive, both forced by the size of these
payloads (gigabytes rather than megabytes):

* the archive is *streamed* — tar into zstd into the output file — instead
  of being assembled in memory;
* the zstd level is 10 rather than 19. Level 19 on a multi-gigabyte
  workspace costs hours for a few per cent; the level is fixed either way,
  which is all determinism asks of it.

**What the source of truth is.** ``west.yml``, ``patches/`` and the Matter
ZAP inputs are read out of a *commit* with ``git archive``, never out of the
working tree — the same rule the SDK archive follows, for the same reason:
an uncommitted edit must not be able to reach a package. The tool downloads
are pinned by version and SHA-256 below.

Usage::

    build_env_package.py workspace --output-dir <dir> [--revision <rev>]
    build_env_package.py tools     --output-dir <dir> [--arch amd64]

Both take ``--version-suffix ci.<sha>`` to build a per-commit package: the
declared version plus a PEP 440 local segment, which is the one shape a
package host will not publish.

Both subcommands do their environment-specific work inside a pinned
container, because neither can be done correctly on an arbitrary host: the
workspace is laid out by the exact ``west`` that will later read it and its
Matter code is generated by the exact ``zap`` the pinned CHIP names, and
the wheel set has to be built by the interpreter of the base image the
environment runs on. The host contributes the downloads, the packing and
nothing else.

Exit status: 0 on success, 2 on a usage error; a failing child command
propagates as a ``CalledProcessError``.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import io
import json
import os
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile
import urllib.request
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import release_lines  # noqa: E402 - repo-relative import, needs the path above

try:
    import zstandard
except ModuleNotFoundError:  # a system python, not the repo's venv
    sys.exit(
        "build_env_package.py needs the zstandard module.\n"
        "Run it from this repository's own venv, which carries it via\n"
        "mcuhome-compiler:\n"
        "    python3 -m venv .venv && . .venv/bin/activate\n"
        "    pip install -e ./packaging/model -e ./packaging/compiler"
    )

#: This repository, seen from ``scripts/``.
REPO_ROOT = Path(__file__).resolve().parent.parent

#: Where :data:`ZEPHYR_RELEASE` is declared, as a path in the repository:
#: this file, read out of the packaged revision (:func:`zephyr_version`).
ZEPHYR_RELEASE_FILE = "scripts/build_env_package.py"

#: The static index, next to the archives it indexes. Same format and same
#: single question as ``scripts/build_sdk_archive.py`` writes it: "which
#: file, and which bytes, for (name, version)".
INDEX_FILE = "index.json"

#: Fixed, and part of what makes two builds of one revision agree. See the
#: module docstring for why it is not the SDK archive's 19.
ZSTD_LEVEL = 10

# --------------------------------------------------------------------------
# The package set
# --------------------------------------------------------------------------

#: Specification §5's ``spec-generation``: the generation this environment
#: implements.
SPEC_GENERATION = "3"

#: The Zephyr release the environment builds against, without the leading
#: ``v``, for the ``zephyr.version`` member of specification §5's
#: declaration.
#:
#: **Lockstep rule: this is the ``revision:`` of the ``zephyr`` project in
#: ``west.yml`` without the ``v``** — bumping one without the other is a
#: bug, and ``tests/python/test_env_package.py`` asserts it. It is restated
#: here rather than parsed out of the manifest because the declaration is
#: written from the *packaged* revision, and this script is read out of
#: that revision for exactly this value (:func:`zephyr_version`) at a point
#: where no YAML parser is available: the release jobs run it on a plain
#: interpreter with one pinned dependency.
ZEPHYR_RELEASE = "4.4.0"

#: The architecture-neutral package. It carries the declaration for the
#: whole set (specification §5) — a set that spans architectures needs a
#: carrier that does not.
WORKSPACE_PACKAGE = "mcuhome-build-workspace"

#: The architecture-specific package *family*. A concrete package appends
#: ``_<os>-<arch>`` (:func:`tools_package_name`); the declaration this
#: script writes names the family, because the bytes differ per platform on
#: purpose and the version is what the platforms have in common.
TOOLS_FAMILY = "mcuhome-build-tools"

#: Specification §5.1's member prefix. The package set is one member per
#: package — ``packages.<full package name>`` — and never a list packed into
#: one value, so a package can be named and looked up on its own, in a JSON
#: object and in an image's labels alike.
PACKAGE_MEMBER_PREFIX = "packages."

#: Where the environment declares itself, at the top of the package that
#: carries it: an unpacked store entry has to be able to say what it is
#: with nothing else present (specification §5).
#:
#: **Inside the archive only.** A copy beside it used to exist for the
#: reader that has not unpacked anything yet; that reader is
#: ``<archive>.meta.json`` now, which answers the question it actually
#: asks — what this package is and what it requires — and answers it for
#: every package rather than for the one that carries the declaration.
#: Two sidecars saying overlapping things is one sidecar too many.
DECLARATION_FILE = "build-environment.json"

#: Specification §9.1's ``build-context.generator-constraint``. An empty
#: specifier means "any build context the workbench produced", which is what
#: this environment accepts today: there is exactly one generator, it is
#: released together with this environment, and no version of it produces a
#: context this environment could not read.
GENERATOR_CONSTRAINT = "mcuhome-workbench:"

# --------------------------------------------------------------------------
# The workspace package
# --------------------------------------------------------------------------

#: Inside the archive: the west workspace top directory. Everything the west
#: tooling owns lives under it, and the package's own metadata lives beside
#: it — a file at the top of the workspace would be shadowed the moment a
#: profile mounts a writable view over the topdir, and it would show up in
#: ``git status`` of whichever project it landed in.
WORKSPACE_DIR = "workspace"

#: Inside the archive: the pre-generated Matter code. See
#: :func:`pregenerate_matter` for the layout inside it and for why the
#: consumer is handed a subdirectory of it rather than this path.
PREGEN_DIR = "matter-pregen"

#: Inside the archive: the record of what was resolved — resolved commit per
#: layer and the SHA-256 of every patch applied. Written by
#: ``packaging/build-environment/workspace-record.py``, which is the one
#: implementation of that document.
RECORD_FILE = "workspace.json"

#: The manifest repository's directory inside the workspace, from
#: ``west.yml``'s ``self: path:``. It is present and **empty** in the
#: package: the SDK is a hash-pinned package fetched per build and delivered
#: by the orchestrator, not environment content.
MANIFEST_DIR = "mcuhome-sdk"

#: What ``west update`` is asked for. ``--narrow -o=--depth=1`` because full
#: history for the manifest's projects is several gigabytes that no build
#: reads. What a build *does* read out of ``.git`` stays: west resolves the
#: ``import:`` of the zephyr project out of ``refs/heads/manifest-rev``, and
#: Zephyr's version stamping shells out to ``git describe``.
CLONE_KIND = "narrow-depth-1"

#: Where CHIP sits inside the workspace — ``west.yml``'s ``path:`` for the
#: ``connectedhomeip`` project. The pre-generation layout is built from this
#: (see :func:`pregenerate_matter`).
CHIP_PATH = "modules/lib/connectedhomeip"

#: The projects that need more than ``west update`` gives them, as
#: ``<west project name>: (<path in the workspace>, <record layer name>)``.
#:
#: They are exactly the two ``west.yml`` pins by *tag* rather than by SHA,
#: and exactly the two ``patches/`` carries a patch for; the patch file names
#: start with the project name, which is the convention
#: ``patches/README.md`` documents.
#:
#: **Tags.** A shallow fetch brings no tags along, and ``git describe`` then
#: answers with the commit instead of the tag — that string becomes
#: ``BUILD_VERSION``, is compiled into the boot banner and changes the
#: firmware bytes. Fetching the tag ref back costs nothing and makes a
#: shallow workspace and a full one produce identical firmware.
#:
#: **Layer names.** ``zephyr``, ``chip`` are what
#: ``packaging/build-environment/workspace-record.py`` knows.
PROJECTS = {
    "zephyr": ("zephyr", "zephyr"),
    "connectedhomeip": (CHIP_PATH, "chip"),
}

#: The module whose binary blobs a build needs and that west does not fetch
#: with the sources. Named here rather than derived, because ``west blobs``
#: has no "everything the manifest allows" mode that would stay honest when
#: the allowlist grows.
BLOB_MODULES = ("hal_espressif",)

#: The Matter data-model configuration inside this repository, without the
#: extension: the ``.zap`` and the ``.matter`` beside it are both inputs.
ZAP_STEM = "components/matter/zap/mcuhome-root"

#: Removed from the workspace tree before it is packed. See :func:`prune`.
PRUNED_DIR = "__pycache__"

# --------------------------------------------------------------------------
# The tools package
# --------------------------------------------------------------------------

#: The Zephyr SDK bundle and the one target toolchain. The *minimal* bundle
#: plus exactly one target toolchain: the full bundle is some twenty
#: architectures and several gigabytes, and MCUHome targets ARM today. This
#: file is the only place these are pinned — they belong to the tools
#: package and to nothing else, and the packager image carries no toolchain
#: at all.
ZEPHYR_SDK_VERSION = "1.0.1"
ZEPHYR_TOOLCHAIN = "arm-zephyr-eabi"

#: gn, which the Matter SDK builds its own libraries with. Taken from the
#: CIPD package Chromium infrastructure publishes and pinned by the gn git
#: revision — ``gn --version`` reports ``2502 (17b0057970fa)``, the version
#: MCUHome verified. Pigweed's own pin inside the pinned CHIP revision is
#: older; MCUHome tracks what it tested rather than what a vendored
#: submodule suggests.
GN_REVISION = "17b0057970fa2b07a20cbb4289ab78cf93565f35"

#: CMake and Ninja, from their projects' own release binaries.
#:
#: **Why upstream binaries and not the base image's packages.** The tools
#: package sets the minimum host baseline for the subprocess profile
#: (design document §6: glibc >= 2.28, set by the Zephyr SDK toolchain).
#: A binary copied out of the Debian trixie base image is linked against
#: trixie's glibc 2.41 and would raise that floor by thirteen releases for
#: two tools that have nothing to do with it. Measured on the two files
#: pinned here, with ``objdump -T``:
#:
#:   * ``cmake`` 3.31.6, linux-x86_64: highest referenced ``GLIBC_2.17``,
#:     and no ``libstdc++`` dependency at all — the C++ runtime is linked
#:     statically.
#:   * ``ninja`` 1.12.1, linux: highest referenced ``GLIBC_2.15`` and
#:     ``GLIBCXX_3.4.19``.
#:
#: Both are below the toolchain's 2.28, so neither moves the floor. The
#: design document's warning about upstream ninja binaries requiring glibc
#: 2.38 applies to *newer* ninja releases; 1.12.1 — the version Debian
#: trixie ships, so the container and the package agree — predates that.
#: ``scripts/lint.d`` cannot check this; :func:`assert_glibc_floor` does,
#: at package build time.
CMAKE_VERSION = "3.31.6"
NINJA_VERSION = "1.12.1"

#: The highest glibc symbol version any binary in the tools package may
#: reference. Design document §6: the floor is set by the Zephyr SDK
#: prebuilt toolchain, and nothing else in the package is allowed to raise
#: it silently.
GLIBC_FLOOR = (2, 28)

#: One versioned glibc symbol reference in ``objdump -T`` output.
GLIBC_SYMBOL = re.compile(r"GLIBC_(\d+)\.(\d+)")

#: Every download of the tools package, per architecture. ``sha256`` is a
#: statement about bytes, so each architecture carries its own — the host
#: spelling differs three ways across the three publishers, which is why
#: each entry resolves its own rather than sharing one variable.
#:
#: Every hash is this file's own, taken from the release artifacts pinned
#: above and verified on every download.
TOOL_DOWNLOADS: dict[str, dict[str, dict[str, str]]] = {
    "amd64": {
        "zephyr-sdk": {
            "url": (
                "https://github.com/zephyrproject-rtos/sdk-ng/releases/download/"
                f"v{ZEPHYR_SDK_VERSION}/zephyr-sdk-{ZEPHYR_SDK_VERSION}_linux-x86_64_minimal.tar.xz"
            ),
            "sha256": "ca9bc0ff66fafca1dac9d592a36d953cf16d096a9d09b1c0357f021cf9f6a7eb",
        },
        "zephyr-toolchain": {
            "url": (
                "https://github.com/zephyrproject-rtos/sdk-ng/releases/download/"
                f"v{ZEPHYR_SDK_VERSION}/toolchain_gnu_linux-x86_64_{ZEPHYR_TOOLCHAIN}.tar.xz"
            ),
            "sha256": "21b85981cb5a1818d9bc53d82af80f208946ec038b982ff1907287572ed3a634",
        },
        "gn": {
            "url": (
                "https://chrome-infra-packages.appspot.com/dl/gn/gn/linux-amd64/+/"
                f"git_revision:{GN_REVISION}"
            ),
            "sha256": "66cba1384b08f05643a31627bdec1d0fcc87ae7d40853ec24ec60b6eb02fe6c9",
        },
        "cmake": {
            "url": (
                f"https://github.com/Kitware/CMake/releases/download/v{CMAKE_VERSION}/"
                f"cmake-{CMAKE_VERSION}-linux-x86_64.tar.gz"
            ),
            "sha256": "5a1133ff103c71eb5120e2cc3de922733e7d8a26a98ae716397e8676adb367bf",
        },
        "ninja": {
            "url": (
                f"https://github.com/ninja-build/ninja/releases/download/v{NINJA_VERSION}/"
                "ninja-linux.zip"
            ),
            "sha256": "6f98805688d19672bd699fbbfa2c2cf0fc054ac3df1f0e6a47664d963d530255",
        },
    },
    "arm64": {
        "zephyr-sdk": {
            "url": (
                "https://github.com/zephyrproject-rtos/sdk-ng/releases/download/"
                f"v{ZEPHYR_SDK_VERSION}/zephyr-sdk-{ZEPHYR_SDK_VERSION}_linux-aarch64_minimal.tar.xz"
            ),
            "sha256": "d79c5bfc68e679488659bea289a4026e52a64f03338875c8c9c850fff13cee30",
        },
        "zephyr-toolchain": {
            "url": (
                "https://github.com/zephyrproject-rtos/sdk-ng/releases/download/"
                f"v{ZEPHYR_SDK_VERSION}/toolchain_gnu_linux-aarch64_{ZEPHYR_TOOLCHAIN}.tar.xz"
            ),
            "sha256": "b9805b691f2f0a8926c92694cae378d05ba07b76abca745e216fcc52753cc4d6",
        },
        "gn": {
            "url": (
                "https://chrome-infra-packages.appspot.com/dl/gn/gn/linux-arm64/+/"
                f"git_revision:{GN_REVISION}"
            ),
            "sha256": "526535a49139b85f812ff3af3b825257896940dc6c6a7c082ceebdd7bcc63f30",
        },
        "cmake": {
            "url": (
                f"https://github.com/Kitware/CMake/releases/download/v{CMAKE_VERSION}/"
                f"cmake-{CMAKE_VERSION}-linux-aarch64.tar.gz"
            ),
            "sha256": "b4cc788d63112b2749b40627e719eb5d3b8ed8f00c36d77189f4019cfe64bc9e",
        },
        "ninja": {
            "url": (
                f"https://github.com/ninja-build/ninja/releases/download/v{NINJA_VERSION}/"
                "ninja-linux-aarch64.zip"
            ),
            "sha256": "5c25c6570b0155e95fce5918cb95f1ad9870df5768653afe128db822301a05a1",
        },
    },
}

#: Inside the tools archive. Fixed names, because the entry point resolves
#: everything else relative to the package root and the profile that unpacks
#: it must not have to be told a layout.
TOOLS_ENTRY = "bin/build-environment-entry"
TOOLS_MANIFEST = "build-tools.json"

#: The entry point's source in this repository.
ENTRY_SOURCE = "packaging/build-environment/build-environment-entry"

#: The pinned Debian base of MCUHome's containers, digest-pinned exactly as
#: ``containers/build-environment-packager/Dockerfile`` and
#: ``containers/build-environment/Dockerfile`` pin it — ``trixie-slim``
#: moves with every point release. It is named here because it decides the
#: wheel set's ABI: the build virtual environment is created by *this*
#: base's Python, so that is the interpreter the wheels have to fit.
#:
#: The wheels are not built in it, though. ``debian:trixie-slim`` carries no
#: interpreter at all (measured: ``python3`` exits 127), and installing one
#: with ``apt-get`` would put an unpinned package into a package build whose
#: whole point is that everything in it is pinned. They are built in the
#: packager image instead, which is this base plus ``python3`` and
#: ``python3-venv`` — pinned as a whole, and the same interpreter.
BASE_IMAGE = (
    "debian:trixie-slim@sha256:3a39a0592364683e6bab97937b72cad5a8fa6dcbbee90edb3bb48c7f8e94f258"
)

#: The pinned Python dependency set of a build, transitive dependencies
#: included — the environment's own, packed into the tools package as a
#: wheel set. Read out of the packaged revision, like everything else.
#: (The much smaller set the *packager* image needs to do the work is a
#: different file, ``containers/build-environment-packager/requirements.txt``.)
REQUIREMENTS_FILE = "packaging/build-environment/requirements.txt"


# --------------------------------------------------------------------------
# git, the source of everything that comes out of this repository
# --------------------------------------------------------------------------


def _git(repository: Path, *arguments: str) -> bytes:
    """One git command against *repository*, its stdout, and no shell."""
    completed = subprocess.run(
        ["git", "-C", str(repository), *arguments],
        check=True,
        stdout=subprocess.PIPE,
    )
    return completed.stdout


def declared_versions(
    repository: Path, commit: str, *, suffix: str | None = None
) -> dict[str, str]:
    """The workspace and tools versions *commit* declares, optionally suffixed.

    Read out of ``packaging/build-environment/environment.json`` at the
    packaged commit rather than out of the working tree: both packages are
    built from a commit, so the names on their files have to describe the
    bytes inside them. The two lines are versioned independently — a new
    toolchain generation moves the tools and nothing else, a ``west.yml``
    change moves the workspace and nothing else — which is why this is two
    numbers and not one.
    """
    document = release_lines.environment(repository, commit)
    return {
        stage: release_lines.suffixed(release_lines.version_of(document, stage), suffix)
        for stage in ("workspace", "tools")
    }


def extract_revision(repository: Path, commit: str, destination: Path, *paths: str) -> None:
    """Check *paths* of *commit* out into *destination*, working tree untouched."""
    destination.mkdir(parents=True, exist_ok=True)
    archive = _git(repository, "archive", "--format=tar", commit, *paths)
    with tarfile.open(fileobj=io.BytesIO(archive), mode="r:") as tar:
        tar.extractall(destination, filter="data")


def commit_timestamp(repository: Path, commit: str) -> int:
    """The commit's own committer date — the archive's single mtime.

    ``SOURCE_DATE_EPOCH`` wins when it is set, which is what a reproducible-
    build environment expects to be able to say.
    """
    override = os.environ.get("SOURCE_DATE_EPOCH")
    if override:
        return int(override)
    return int(_git(repository, "show", "-s", "--format=%ct", commit).decode().strip())


# --------------------------------------------------------------------------
# The deterministic archive
# --------------------------------------------------------------------------


@dataclass(frozen=True)
class Package:
    """One built package: the file, and everything the index says about it."""

    path: Path
    name: str
    version: str
    sha256: str
    size: int


def _members(root: Path) -> list[tuple[str, Path]]:
    """Every member of *root* as ``(archive name, path)``, sorted by byte order.

    Sorted on the encoded name rather than on the string, because the archive
    order has to be a property of the bytes and not of a locale. Directories
    are emitted too — including empty ones, which a package can carry and
    ``git archive`` could not (the SDK mount point is exactly one).
    """
    found: list[tuple[bytes, str, Path]] = []
    for path in root.rglob("*"):
        name = path.relative_to(root).as_posix()
        found.append((name.encode("utf-8"), name, path))
    found.sort(key=lambda item: item[0])
    return [(name, path) for _, name, path in found]


def write_archive(root: Path, target: Path, *, mtime: int) -> tuple[str, int]:
    """Pack *root* into *target* as a deterministic ``.tar.zst``; digest and size.

    PAX rather than GNU: it is the POSIX-2001 format with a defined answer
    for everything an extractor might meet, and Python's writer emits an
    extended header only for a field that does not fit — with an integer
    *mtime*, ``uid``/``gid`` 0 and no path over 100 bytes, that is none of
    them here.

    Modes are narrowed to 0755 and 0644. The exec bit is the one mode fact a
    consumer reads — a toolchain full of compilers, ``gn``, ``ninja`` and the
    entry point are all spawned as children — and everything else a
    filesystem's umask happens to carry is noise that would change the
    digest.

    Streamed rather than assembled: tar writes into the zstd compressor,
    which writes into the file, and the digest is taken on the way past. A
    workspace package is several gigabytes and does not fit anywhere else.
    """
    digest = hashlib.sha256()
    size = 0

    class _Tap(io.RawIOBase):
        """The output file, hashed and counted as it is written."""

        def __init__(self, handle: io.BufferedWriter) -> None:
            self._handle = handle

        def writable(self) -> bool:
            return True

        def write(self, data) -> int:  # noqa: ANN001 - a buffer protocol object
            nonlocal size
            chunk = bytes(data)
            digest.update(chunk)
            size += len(chunk)
            self._handle.write(chunk)
            return len(chunk)

    # threads=0 because a multi-threaded compressor splits the input into
    # jobs and produces different bytes for the same input. The checksum is
    # off and the content size is off as well: in a streaming frame the
    # length is not known when the header is written, so leaving it out is
    # the one answer that does not depend on which API knew what.
    compressor = zstandard.ZstdCompressor(
        level=ZSTD_LEVEL,
        write_checksum=False,
        write_content_size=False,
        threads=0,
    )

    target.parent.mkdir(parents=True, exist_ok=True)
    with open(target, "wb") as handle:
        tap = io.BufferedWriter(_Tap(handle))
        writer = compressor.stream_writer(tap, closefd=False)
        with writer, tarfile.open(fileobj=writer, mode="w|", format=tarfile.PAX_FORMAT) as tar:
            _add_members(tar, root, mtime=mtime)
        tap.flush()
    return digest.hexdigest(), size


def _add_members(tar: tarfile.TarFile, root: Path, *, mtime: int) -> None:
    """Every member of *root*, normalized to the fields a package may carry."""
    for name, path in _members(root):
        info = tarfile.TarInfo(name)
        info.mtime = mtime
        info.uid = 0
        info.gid = 0
        info.uname = ""
        info.gname = ""
        if path.is_symlink():
            info.type = tarfile.SYMTYPE
            info.mode = 0o777
            info.linkname = os.readlink(path)
            tar.addfile(info)
        elif path.is_dir():
            info.type = tarfile.DIRTYPE
            info.mode = 0o755
            tar.addfile(info)
        elif path.is_file():
            info.type = tarfile.REGTYPE
            info.mode = 0o755 if path.stat().st_mode & 0o111 else 0o644
            info.size = path.stat().st_size
            with open(path, "rb") as content:
                tar.addfile(info, content)
        else:
            raise SystemExit(
                f"{path} is neither a regular file, a directory nor a symbolic "
                "link — a package carries nothing else"
            )


def tools_package_name(os_name: str, arch: str) -> str:
    """The concrete tools package of one platform: ``<family>_<os>-<arch>``.

    ``_`` and not another ``-``: a package name is otherwise lowercase
    alphanumerics and ``-``, so the first ``_`` is the one character that
    splits the family from the platform without anybody having to know the
    family's name first (specification §5.1).
    """
    return f"{TOOLS_FAMILY}_{os_name}-{arch}"


def package_filename(name: str, version: str) -> str:
    """``<name>-<version>.tar.zst`` — the file-name scheme for every package.

    *name* is the full package name, architecture suffix included, so the
    tools package of one platform is
    ``mcuhome-build-tools_linux-amd64-<version>.tar.zst``.
    """
    return f"{name}-{version}.tar.zst"


def sidecar_entry(path: Path) -> dict:
    """One sidecar as an index entry: which file, which bytes, how many.

    The same three fields the archive's own entry carries, because the
    question is the same one — a reader that has the index has everything
    it needs to fetch the file and check it before trusting a word of it.
    """
    payload = path.read_bytes()
    return {
        "file": path.name,
        "sha256": hashlib.sha256(payload).hexdigest(),
        "size": len(payload),
    }


def write_index(
    path: Path,
    *,
    package: str,
    version: str,
    file: str,
    sha256: str,
    size: int,
    meta_file: dict | None = None,
):
    """Record this package in the static index, keeping the versions already there.

    The index answers exactly one question — "which file, and which bytes,
    for ``(name, version)``". A URL here would be a second, weaker answer to
    a question the operator's source list already answers. An existing index
    is read and extended rather than replaced; an unreadable one is a
    refusal, never an overwrite, because it is the only record of the
    packages already in that directory.

    ``meta_file`` records the meta sidecar the same way, under the name the
    package registry's index uses for it — so whoever resolves a release
    chain finds it identically in an operator's directory and on a host.
    The key is ``meta_file`` and not ``meta`` because ``meta`` already means
    something else in that index: it is the member that makes an entry a
    *meta package*, the family that maps platforms onto concrete packages.
    """
    document: dict = {"packages": {}}
    if path.exists():
        try:
            found = json.loads(path.read_text(encoding="utf-8"))
        except ValueError as failure:
            raise SystemExit(f"{path} is not readable as JSON: {failure}") from failure
        if not isinstance(found, dict) or not isinstance(found.get("packages"), dict):
            raise SystemExit(f"{path} is not an index: no packages object")
        document = found
    entry: dict = {"file": file, "sha256": sha256, "size": size}
    if meta_file is not None:
        entry["meta_file"] = meta_file
    document["packages"].setdefault(package, {})[version] = entry
    path.write_text(
        json.dumps(document, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def publish(
    root: Path, output_dir: Path, *, name: str, version: str, mtime: int, meta: bytes
) -> Package:
    """Pack *root*, write the sidecars and the index, and say what came out.

    *meta* is written on both sides of the archive from this one value —
    at the top of the tree before it is packed, and beside the archive
    afterwards — so the copy a reader happens to take cannot decide what
    the package is. Inside, because an unpacked store entry has to be able
    to say what it is with nothing else present; beside, because whoever
    resolves a release chain reads what a package requires before it
    fetches a gigabyte of it.
    """
    (root / release_lines.META_FILE).write_bytes(meta)
    output_dir.mkdir(parents=True, exist_ok=True)
    archive = output_dir / package_filename(name, version)
    digest, size = write_archive(root, archive, mtime=mtime)
    sidecar = output_dir / f"{archive.name}{release_lines.META_SUFFIX}"
    sidecar.write_bytes(meta)
    # sha256sum's own format — bare hex, two spaces, the file name — so
    # `sha256sum -c` checks a mirrored copy with no tooling of ours.
    (output_dir / f"{archive.name}.sha256").write_text(
        f"{digest}  {archive.name}\n", encoding="utf-8"
    )
    write_index(
        output_dir / INDEX_FILE,
        package=name,
        version=version,
        file=archive.name,
        sha256=digest,
        size=size,
        meta_file=sidecar_entry(sidecar),
    )
    return Package(path=archive, name=name, version=version, sha256=digest, size=size)


# --------------------------------------------------------------------------
# Specification §5: the self-description
# --------------------------------------------------------------------------


def zephyr_version(repository: Path, commit: str) -> str:
    """The Zephyr release this environment builds against, without the ``v``.

    Read out of *this script* at the packaged revision rather than taken
    from the running process: a package is built from a commit, so the
    number that goes into its declaration is that commit's
    :data:`ZEPHYR_RELEASE` and not the working tree's.
    """
    source = _git(repository, "cat-file", "blob", f"{commit}:{ZEPHYR_RELEASE_FILE}")
    for node in ast.parse(source.decode("utf-8")).body:
        if not isinstance(node, ast.Assign):
            continue
        named = (target.id for target in node.targets if isinstance(target, ast.Name))
        if "ZEPHYR_RELEASE" not in named:
            continue
        value = ast.literal_eval(node.value)
        if isinstance(value, str):
            return value
    raise SystemExit(f"{commit} declares no string ZEPHYR_RELEASE in {ZEPHYR_RELEASE_FILE}")


def package_members(workspace_version: str, tools_version: str) -> dict[str, str]:
    """Specification §5.1's package members: one member per package.

    ``packages.<full package name>``, value ``<version>`` or
    ``<version>@sha256:<digest>``. What this script writes is the
    **abstract** set §5.1 asks a package's own metadata for, and both of its
    two rules apply here:

    * The carrier states no hash of its own. The declaration is inside the
      archive it would be describing, so the hash would have to cover bytes
      that contain it.
    * The tools entry names the *family* rather than one platform's package,
      at version level only — the sibling platforms' archives may not even
      exist yet when this one is packed, and their bytes differ on purpose.

    The concrete, fully hashed set is stated by whoever holds the exact
    bytes: ``scripts/build_env_image.py`` does it for the container profile,
    completing this document rather than replacing it.
    """
    return {
        f"{PACKAGE_MEMBER_PREFIX}{TOOLS_FAMILY}": tools_version,
        f"{PACKAGE_MEMBER_PREFIX}{WORKSPACE_PACKAGE}": workspace_version,
    }


def declaration(*, zephyr: str, workspace_version: str, tools_version: str) -> dict[str, str]:
    """The whole §5 declaration. Every member is a string; that is the format."""
    return {
        "spec-generation": SPEC_GENERATION,
        "zephyr.version": zephyr,
        "build-context.generator-constraint": GENERATOR_CONSTRAINT,
        **package_members(workspace_version, tools_version),
    }


def write_json(path: Path, document: dict) -> None:
    """One JSON document, formatted the one way this script formats them."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(document, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


# --------------------------------------------------------------------------
# Containers — where the work that cannot be done on an arbitrary host runs
# --------------------------------------------------------------------------


def run_in_container(image: str, mounts: dict[Path, str], script: str, *, network: bool) -> None:
    """Run *script* with ``/bin/sh`` inside *image*, as the calling user.

    As the calling user (``--user``) so that everything it writes into the
    mounts belongs to whoever is building the package and not to root — a
    package build must not need a privileged cleanup afterwards. ``HOME`` is
    pointed at a writable directory because that user has no entry in the
    image's ``/etc/passwd`` and several tools insist on having one.
    """
    command = ["docker", "run", "--rm", "--user", f"{os.getuid()}:{os.getgid()}"]
    if not network:
        command += ["--network", "none"]
    for source, destination in mounts.items():
        command += ["--volume", f"{source}:{destination}"]
    command += ["--env", "HOME=/tmp"]
    epoch = os.environ.get("SOURCE_DATE_EPOCH")
    if epoch:
        command += ["--env", f"SOURCE_DATE_EPOCH={epoch}"]
    command += [image, "/bin/sh", "-euc", script]
    subprocess.run(command, check=True)


def packager_image(override: str | None = None) -> str:
    """The packager image to run in, from the one place that names it.

    *override* is what ``--packager-image`` was given, and exists for the
    two occasions on which the pinned reference cannot be used: publishing
    the packager for the first time, when no digest exists yet, and trying
    a change to ``containers/build-environment-packager/`` before it is
    published. A package built with an override is not a package anybody
    else can reproduce, which is why it is a deliberate flag and never a
    fallback.
    """
    if override:
        return override
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    from packager_image import reference  # noqa: PLC0415 - repo-relative import

    return reference()


# --------------------------------------------------------------------------
# Downloads
# --------------------------------------------------------------------------


def fetch(url: str, sha256: str, cache: Path) -> Path:
    """Download *url* into *cache* unless it is already there, and verify it.

    The hash is the whole point: a package that silently absorbs a re-tagged
    upstream artifact is not a reproducible build environment. A cached file
    is verified again rather than trusted, so a truncated download from an
    earlier run cannot survive into a package.
    """
    cache.mkdir(parents=True, exist_ok=True)
    target = cache / sha256
    if not target.exists():
        print(f"  fetching {url}", flush=True)
        with urllib.request.urlopen(url) as response, open(target, "wb") as handle:
            shutil.copyfileobj(response, handle)
    digest = hashlib.sha256()
    with open(target, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    if digest.hexdigest() != sha256:
        target.unlink()
        raise SystemExit(f"{url} is not the pinned artifact: {digest.hexdigest()} != {sha256}")
    return target


# --------------------------------------------------------------------------
# The workspace package
# --------------------------------------------------------------------------


def materialize_workspace(*, source: Path, work: Path, image: str) -> None:
    """Lay the west workspace out, patch it, fetch its blobs, record it.

    Each step is there for a reason stated at its constant: shallow update,
    tag refs fetched back, patches applied as working-tree changes, blobs
    fetched, the record written, and only then the manifest repository's
    directory emptied — the record needs the manifest to read the workspace,
    and the SDK is mounted per build rather than packaged.

    It runs inside the pinned packager image because the west that lays a
    workspace out and the west that reads it later have to be one version,
    and that image is where the pinned one lives.
    """
    workspace = work / WORKSPACE_DIR
    (workspace / MANIFEST_DIR).mkdir(parents=True, exist_ok=True)
    shutil.copy2(source / "west.yml", workspace / MANIFEST_DIR / "west.yml")

    steps = [
        f"cd /work/{WORKSPACE_DIR}",
        # `west init -l` needs exactly one file of the manifest repository:
        # west.yml. It never asks whether the directory is a git repository,
        # which is what makes it possible to lay a workspace out from a bare
        # copy of the manifest and deliver the real SDK into it later.
        f"west init -l {MANIFEST_DIR}",
        # Deliberately without a group-filter: the `matter` group is wanted
        # here — this is the environment that builds Matter firmware.
        "west update --narrow -o=--depth=1",
    ]
    for project, (path, _layer) in PROJECTS.items():
        # The remote is asked for rather than named: west calls it after the
        # manifest's `remotes:` entry, never `origin`, and each project has
        # exactly one — so taking the first is both correct and indifferent
        # to what it is called.
        steps.append(
            f'revision="$(west list -f "{{revision}}" {project})"; '
            f'remote="$(git -C {path} remote | head -n1)"; '
            f'test -n "$remote"; '
            f'git -C {path} fetch --depth=1 "$remote" '
            f'"refs/tags/$revision:refs/tags/$revision"'
        )
    for project, (path, _layer) in PROJECTS.items():
        # The patch set, applied the way patches/README.md documents it:
        # `git apply`, nothing else — no --3way, no --reject, no retry. A
        # patch that has drifted from the revision west.yml pins fails the
        # package build, loudly, right here.
        #
        # Left as working-tree changes, NOT committed: committing moves
        # `git describe` from the tag to `<tag>-1-g<sha>` and therefore
        # changes BUILD_VERSION, the banner and the firmware.
        steps.append(
            f"for patch in /src/patches/{project}-*.patch; do "
            f'git -C {path} apply --verbose "$patch"; done'
        )
    # The binary blobs west deliberately does not fetch with the sources. A
    # build with no network cannot fetch them later, so the package carries
    # them or the module is unusable.
    steps += [f"west blobs fetch {module}" for module in BLOB_MODULES]
    # Pre-populated so no lazy configuration write ever happens on a
    # read-only tree: west's zephyr extension writes zephyr.base on first
    # use, and in a frozen store there is nowhere to write it.
    steps.append("west config zephyr.base zephyr")

    run_in_container(image, {work: "/work", source: "/src"}, "\n".join(steps), network=True)


def record_workspace(*, source: Path, work: Path, image: str) -> None:
    """Write the workspace record, then empty the manifest repository's directory.

    One implementation of that document exists —
    ``packaging/build-environment/workspace-record.py``, which is packaging
    material rather than image content. It has to run before the manifest
    repository's directory is emptied, because it reads the workspace
    through west.
    """
    patch_arguments: list[str] = []
    for project, (_path, layer) in PROJECTS.items():
        for patch in sorted((source / "patches").glob(f"{project}-*.patch")):
            patch_arguments += ["--patch", f"{layer}=/src/patches/{patch.name}"]

    script = "\n".join(
        [
            "python3 /src/packaging/build-environment/workspace-record.py "
            f"--topdir /work/{WORKSPACE_DIR} --output /work/{RECORD_FILE} "
            f"--clone {CLONE_KIND} " + " ".join(patch_arguments),
            # The manifest repository's directory is emptied and left in
            # place. west needed west.yml to get here; the orchestrator
            # brings the SDK back at run time, because it is a hash-pinned
            # package chosen per build rather than environment content.
            f"rm -rf /work/{WORKSPACE_DIR}/{MANIFEST_DIR}",
            f"mkdir /work/{WORKSPACE_DIR}/{MANIFEST_DIR}",
        ]
    )
    run_in_container(image, {work: "/work", source: "/src"}, script, network=False)


def pregen_chip_root() -> str:
    """Where a consumer is told the pre-generated code is.

    CHIP's CMake glue indexes the pre-generation directory by the path of the
    data-model file **relative to CHIP_ROOT**
    (``build/chip/chip_codegen.cmake``): it computes
    ``${CHIP_CODEGEN_PREGEN_DIR}/${relative path without extension}/codegen/<generator>``
    and the same with ``/zap/``. Our data model lives in the SDK, outside
    CHIP, so that relative path climbs out of the CHIP tree and back down
    into the manifest repository's directory.

    So the pre-generation directory is laid out as a **shadow of the
    workspace**, and the consumer is handed the shadow's CHIP root. Then
    "relative to CHIP_ROOT" means the same thing in the shadow as in the
    workspace, and nothing has to agree about how deep anything is.

    The shadow's CHIP root is an **empty directory** the package carries on
    purpose. The path a compiler is handed keeps the ``..`` in it, and the
    kernel resolves ``..`` by walking, not by rewriting the string: every
    component in front of it has to exist or the whole path is ENOENT.
    Measured — without the empty directory the include path resolves to
    nothing and the first CHIP header out of the pre-generated tree is not
    found.
    """
    return f"{PREGEN_DIR}/{CHIP_PATH}"


def pregenerate_matter(*, source: Path, work: Path, image: str) -> None:
    """Generate the Matter data-model code the build would otherwise make itself.

    Two generators, because a Matter application build asks for two
    (``src/app/chip_data_model.cmake``):

    ``codegen/cpp-app``
        from the ``.matter`` IDL, by ``scripts/codegen.py`` — pure Python.
    ``zap/app-templates``
        from the ``.zap``, by ``scripts/tools/zap/generate.py`` — the one
        step that needs the ``zap`` tool, and the reason this happens here:
        zap is distributed only as an Electron application and needs a
        desktop shared-library set no lean host baseline should carry.
        MCUHome's input is a single static root-node configuration that
        changes only with a release, so its output is a release constant.

    They are invoked directly rather than through ``scripts/codepregen.py``.
    codepregen walks a root and derives its output paths from *that* root,
    which does not agree with what the consumer computes for a data model
    outside CHIP; and its ZAP target passes no ``--zcl``, which an
    out-of-tree ``.zap`` needs, because the path stored inside the file is
    relative to CHIP's own example directories
    (``components/matter/zap/README.md``). The two invocations below are the
    ones that README documents, pointed at the exact directories the build
    reads.
    """
    workspace = f"/work/{WORKSPACE_DIR}"
    chip = f"{workspace}/{CHIP_PATH}"
    # The path of the data model relative to CHIP_ROOT, spelled out in the
    # shadow: <pregen>/<manifest dir>/<zap stem>. See pregen_chip_root().
    shadow = f"/work/{PREGEN_DIR}/{MANIFEST_DIR}/{ZAP_STEM}"

    script = "\n".join(
        [
            f"mkdir -p {shadow}/codegen/cpp-app {shadow}/zap/app-templates/zap-generated "
            f"/work/{pregen_chip_root()}",
            # scripts/pyshim/ stands in for CHIP's `python_path` helper, which
            # the v1.5.1.0 release tarball ships without and its codegen
            # imports.
            "export PYTHONPATH=/src/scripts/pyshim",
            # The .matter IDL half. --generator cpp-app is what
            # chip_configure_data_model() asks chip_codegen() for.
            f"python3 {chip}/scripts/codegen.py --generator cpp-app "
            f"--output-dir {shadow}/codegen/cpp-app "
            f"/src/{ZAP_STEM}.matter",
            # The .zap half. --zcl is required: the path stored inside the
            # .zap is relative to CHIP's own example directories and does not
            # resolve from here — the build passes the same path via
            # chip_configure_data_model(... ZCL_PATH ...) for that reason.
            f"python3 {chip}/scripts/tools/zap/generate.py /src/{ZAP_STEM}.zap "
            f"--templates {chip}/src/app/zap-templates/app-templates.json "
            f"--zcl {chip}/src/app/zap-templates/zcl/zcl.json "
            f"--no-prettify-output -o {shadow}/zap/app-templates/zap-generated",
        ]
    )
    run_in_container(image, {work: "/work", source: "/src"}, script, network=False)


def prune(root: Path) -> None:
    """Remove what the package build left behind and no build reads.

    Laying the workspace out and pre-generating the Matter code runs Python
    out of the source trees, and Python writes a ``__pycache__`` beside
    every module it imports. Those files are not part of the workspace
    ``west.yml`` describes; they are byproducts of *this* build, they carry
    the source file's timestamp and size in their header, and a read-only
    store cannot use them anyway — CPython simply skips the cache it cannot
    write. Shipping them would put a few megabytes of nothing into the
    package and make two builds of one revision differ for a reason that has
    no relation to the revision.
    """
    for path in sorted(root.rglob(PRUNED_DIR), reverse=True):
        if path.is_dir():
            shutil.rmtree(path)


def applied_patches(source: Path) -> list[str]:
    """The patch files this package build applies, in the order it applies them.

    The names alone, because that is what a reader of the meta file wants
    to know ("which patches are in here"); the record inside the package
    identifies each one by its SHA-256 as well, which is the identity
    ``patches/README.md`` makes necessary — a patch is regenerated in
    place, keeping its file name.
    """
    return [
        patch.name
        for project in PROJECTS
        for patch in sorted((source / "patches").glob(f"{project}-*.patch"))
    ]


def workspace_contents(*, record: dict, patches: list[str], document: dict[str, str]) -> dict:
    """What the workspace package resolved to, for its meta file.

    Three answers, and each of them is a question somebody has had to ask
    a package by unpacking it:

    ``projects``
        Every west project the workspace carries — the manifest's own and
        every one imported through it — with the revision the manifest
        pins and the commit that revision resolved to. Two of those pins
        are *tags*, and a tag is movable at the remote, so "which bytes"
        and "which pin" are different facts and both are stated.
    ``patches``
        Which patch files were applied on top.
    ``environment``
        The §5 declaration this package carries, repeated here so that a
        reader of the meta file sees the package set an image assembles
        from it without opening the archive.
    """
    projects = record.get("projects", {})
    return {
        "environment": dict(document),
        "patches": patches,
        "projects": {
            name: {
                "path": project["path"],
                "pinned": project["revision"],
                "revision": project["commit"],
                "url": project["url"],
            }
            for name, project in sorted(projects.items())
        },
    }


def build_workspace_package(
    *,
    repository: Path,
    revision: str,
    output_dir: Path,
    work: Path,
    image: str,
    version_suffix: str | None = None,
):
    """The whole workspace package, from a commit to a file."""
    commit = _git(repository, "rev-parse", "--verify", f"{revision}^{{commit}}").decode().strip()
    versions = declared_versions(repository, commit, suffix=version_suffix)
    version = versions["workspace"]
    mtime = commit_timestamp(repository, commit)

    source = work / "source"
    if source.exists():
        shutil.rmtree(source)
    extract_revision(
        repository,
        commit,
        source,
        "west.yml",
        "patches",
        "scripts/pyshim",
        "packaging/build-environment/workspace-record.py",
        f"{ZAP_STEM}.zap",
        f"{ZAP_STEM}.matter",
    )

    root = work / "root"
    if root.exists():
        shutil.rmtree(root)
    root.mkdir(parents=True)

    print("materializing the west workspace", flush=True)
    materialize_workspace(source=source, work=root, image=image)
    print("recording the workspace", flush=True)
    record_workspace(source=source, work=root, image=image)
    print("pre-generating the Matter data model", flush=True)
    pregenerate_matter(source=source, work=root, image=image)
    prune(root)

    document = declaration(
        zephyr=zephyr_version(repository, commit),
        workspace_version=version,
        tools_version=versions["tools"],
    )
    meta = release_lines.json_bytes(
        release_lines.meta_document(
            name=WORKSPACE_PACKAGE,
            version=version,
            architecture=None,
            requires=release_lines.requires_of(
                release_lines.environment(repository, commit), "workspace"
            ),
            inputs=release_lines.inputs_sha256("workspace", commit, repository=repository),
            contents=workspace_contents(
                record=json.loads((root / RECORD_FILE).read_text(encoding="utf-8")),
                patches=applied_patches(source),
                document=document,
            ),
        )
    )
    # Where the parts of this package are, said by the package rather than
    # guessed by whoever unpacks it. `matter-pregen-chip-root` is the value
    # a build passes as CHIP_CODEGEN_PREGEN_DIR (see pregen_chip_root).
    write_json(
        root / "build-workspace.json",
        {
            "package": WORKSPACE_PACKAGE,
            "version": version,
            "commit": commit,
            "workspace": WORKSPACE_DIR,
            "workspace-record": RECORD_FILE,
            "manifest-directory": f"{WORKSPACE_DIR}/{MANIFEST_DIR}",
            "matter-pregen-chip-root": pregen_chip_root(),
        },
    )

    print("packing", flush=True)
    return publish_workspace(
        root, output_dir, version=version, mtime=mtime, document=document, meta=meta
    )


def publish_workspace(
    root: Path,
    output_dir: Path,
    *,
    version: str,
    mtime: int,
    document: dict[str, str],
    meta: bytes,
) -> Package:
    """Pack the workspace package with the §5 declaration at the top of it.

    One function rather than two calls at the call site, because the
    declaration has to be written before the archive is packed and only
    the workspace package carries one: it is the architecture-neutral
    member of the set, and a set that spans architectures needs a carrier
    that does not.

    The declaration and the meta file are two documents and stay two: the
    declaration is what the *specification* asks a build environment for
    and what an image mirrors into its labels, the meta file is what
    MCUHome's own release chain asks a *package* for. Their audiences
    differ, and so does what they may contain — which is also why only one
    of them is published beside the archive.
    """
    write_json(root / DECLARATION_FILE, document)
    return publish(
        root, output_dir, name=WORKSPACE_PACKAGE, version=version, mtime=mtime, meta=meta
    )


# --------------------------------------------------------------------------
# The tools package
# --------------------------------------------------------------------------


def assert_glibc_floor(root: Path) -> None:
    """Refuse a package whose binaries need a newer glibc than the baseline.

    Design document §6 sets the floor at glibc 2.28, from the Zephyr SDK
    prebuilt toolchain. A tool that quietly needs a newer one does not fail
    where it is built — it fails on somebody's host, months later, with a
    link error nobody can place. ``objdump`` reads the versioned symbol
    references out of every *host* ELF file in the package; the highest one
    is the floor.

    Skipped, with a notice, when ``objdump`` is not installed: the check is
    worth running wherever it can run, and a missing binutils is not a
    reason to refuse to build a package.
    """
    if shutil.which("objdump") is None:
        print("  objdump not installed — glibc floor not checked", flush=True)
        return
    highest = (0, 0)
    culprit = ""
    for path in root.rglob("*"):
        if not path.is_file() or path.is_symlink():
            continue
        with open(path, "rb") as handle:
            header = handle.read(20)
        if header[:4] != b"\x7fELF" or len(header) < 20:
            continue
        # Only the *host* binaries can raise the host baseline. The Zephyr
        # SDK is mostly target objects — tens of thousands of them — and
        # asking objdump about each would cost minutes to learn that an ARM
        # object references no glibc symbol. ``e_machine`` is two bytes at
        # offset 18, little-endian on both hosts this package is built for:
        # 62 is x86-64, 183 is AArch64.
        if int.from_bytes(header[18:20], "little") not in (62, 183):
            continue
        completed = subprocess.run(
            ["objdump", "-T", str(path)], stdout=subprocess.PIPE, stderr=subprocess.DEVNULL
        )
        # Searched rather than tokenized: objdump prints a symbol's version
        # bare for the default version and in parentheses for every other
        # one — `GLIBC_2.17 fopen` next to `(GLIBC_2.2.5) __register_atfork`
        # — and the parenthesized ones are exactly the older references a
        # floor is made of.
        for major, minor in GLIBC_SYMBOL.findall(completed.stdout.decode("utf-8", "replace")):
            version = (int(major), int(minor))
            if version > highest:
                highest, culprit = version, path.relative_to(root).as_posix()
    print(f"  highest glibc requirement: {highest[0]}.{highest[1]} ({culprit})", flush=True)
    if highest > GLIBC_FLOOR:
        raise SystemExit(
            f"{culprit} needs glibc {highest[0]}.{highest[1]}, above the "
            f"{GLIBC_FLOOR[0]}.{GLIBC_FLOOR[1]} host baseline this package promises"
        )


def unpack_tools(*, arch: str, cache: Path, root: Path) -> None:
    """Every pinned download, verified and unpacked into the package tree."""
    downloads = TOOL_DOWNLOADS[arch]

    sdk_dir = root / f"zephyr-sdk-{ZEPHYR_SDK_VERSION}"
    # The toolchain archive unpacks to `<toolchain>/`, and the SDK expects it
    # under `gnu/` — which is what the SDK's own setup.sh does with it, minus
    # the interactive prompts and the host-tool installer. The SDK's host
    # tools (qemu, openocd, a second dtc) are deliberately not installed.
    archive = fetch(downloads["zephyr-sdk"]["url"], downloads["zephyr-sdk"]["sha256"], cache)
    with tarfile.open(archive, mode="r:xz") as tar:
        tar.extractall(root, filter="tar")
    shutil.rmtree(sdk_dir / "hosttools", ignore_errors=True)
    (sdk_dir / "gnu").mkdir(parents=True, exist_ok=True)
    archive = fetch(
        downloads["zephyr-toolchain"]["url"], downloads["zephyr-toolchain"]["sha256"], cache
    )
    with tarfile.open(archive, mode="r:xz") as tar:
        tar.extractall(sdk_dir / "gnu", filter="tar")

    # gn — one binary in a zip.
    archive = fetch(downloads["gn"]["url"], downloads["gn"]["sha256"], cache)
    (root / "gn").mkdir(parents=True, exist_ok=True)
    shutil.unpack_archive(archive, root / "gn", format="zip")
    (root / "gn" / "gn").chmod(0o755)

    # CMake — the upstream tree, with the version directory flattened away so
    # the entry point does not have to know the version to build a PATH.
    archive = fetch(downloads["cmake"]["url"], downloads["cmake"]["sha256"], cache)
    with tempfile.TemporaryDirectory(dir=root.parent) as staging:
        with tarfile.open(archive, mode="r:gz") as tar:
            tar.extractall(staging, filter="tar")
        (unpacked,) = list(Path(staging).iterdir())
        shutil.move(str(unpacked), str(root / "cmake"))

    # Ninja — one binary in a zip.
    archive = fetch(downloads["ninja"]["url"], downloads["ninja"]["sha256"], cache)
    (root / "ninja").mkdir(parents=True, exist_ok=True)
    shutil.unpack_archive(archive, root / "ninja", format="zip")
    (root / "ninja" / "ninja").chmod(0o755)


def build_wheels(*, source: Path, root: Path, mtime: int, image: str) -> None:
    """Build the complete wheel set the build virtual environment is created from.

    Wheels rather than a ready virtual environment, because a virtual
    environment is not relocatable — absolute interpreter paths, absolute
    shebangs — so provisioning creates it at its final location, offline.
    Everything is built to a wheel here (``pip wheel``) rather than left as
    an sdist: some transitive dependencies ship as sdists by default, and
    building those during provisioning would be fragile on a host with no
    network and no compiler.

    Built in a container, because the interpreter that builds the wheels
    decides which interpreter can install them, and the one the environment
    runs on is :data:`BASE_IMAGE`'s — see there for why the packager image
    supplies it rather than the base itself. ``/usr/bin/python3`` explicitly:
    the packager image puts its own virtual environment first on ``PATH``, and
    a virtual environment inside a virtual environment is not what decides an
    ABI. ``SOURCE_DATE_EPOCH`` is what makes a locally built wheel
    reproducible: without it the zip carries the build time, and the two
    dependencies that arrive as sdists would differ between two package
    builds for no reason.
    """
    wheels = root / "wheels"
    wheels.mkdir(parents=True, exist_ok=True)
    script = "\n".join(
        [
            "/usr/bin/python3 -m venv /tmp/wheelbuild",
            "/tmp/wheelbuild/bin/pip wheel --disable-pip-version-check "
            f"--no-cache-dir -r /src/{REQUIREMENTS_FILE} -w /out",
        ]
    )
    previous = os.environ.get("SOURCE_DATE_EPOCH")
    os.environ["SOURCE_DATE_EPOCH"] = str(mtime)
    try:
        run_in_container(image, {source: "/src", wheels: "/out"}, script, network=True)
    finally:
        if previous is None:
            del os.environ["SOURCE_DATE_EPOCH"]
        else:
            os.environ["SOURCE_DATE_EPOCH"] = previous


def requirement_version(requirements: Path, package: str) -> str:
    """The version *requirements* pins *package* at, or a refusal.

    The environment's own requirement set is the one place its Python
    dependencies are pinned, and the package build reads it out of the
    packaged commit — so the version the meta file reports for ``west`` is
    the version the wheel set actually holds.
    """
    for line in requirements.read_text(encoding="utf-8").splitlines():
        name, separator, version = line.strip().partition("==")
        if separator and name.lower() == package:
            return version
    raise SystemExit(f"{requirements} pins no {package}")


def tools_contents(*, arch: str, os_name: str, python: str, west: str) -> dict:
    """Which tools this package carries, at which versions.

    Everything a build compiles with, in one place a reader can compare
    two packages by: the toolchain and the three build tools are pinned in
    this script, the interpreter is the packager's base — it decides the
    wheel set's ABI and therefore travels with the package — and ``west``
    comes out of the environment's own requirement set.
    """
    return {
        "architecture": f"{os_name}-{arch}",
        "tools": {
            "cmake": CMAKE_VERSION,
            "gn": GN_REVISION,
            "ninja": NINJA_VERSION,
            "python": python,
            "toolchain": ZEPHYR_TOOLCHAIN,
            "west": west,
            "zephyr-sdk": ZEPHYR_SDK_VERSION,
        },
    }


def build_tools_package(
    *,
    repository: Path,
    revision: str,
    output_dir: Path,
    work: Path,
    arch: str,
    os_name: str,
    image: str,
    version_suffix: str | None = None,
):
    """The whole tools package, from pins and a commit to a file."""
    if arch not in TOOL_DOWNLOADS:
        raise SystemExit(f"no downloads pinned for {arch!r}: {sorted(TOOL_DOWNLOADS)}")
    commit = _git(repository, "rev-parse", "--verify", f"{revision}^{{commit}}").decode().strip()
    version = declared_versions(repository, commit, suffix=version_suffix)["tools"]
    mtime = commit_timestamp(repository, commit)
    name = tools_package_name(os_name, arch)

    source = work / "source"
    if source.exists():
        shutil.rmtree(source)
    extract_revision(repository, commit, source, REQUIREMENTS_FILE, ENTRY_SOURCE)

    root = work / "root"
    if root.exists():
        shutil.rmtree(root)
    root.mkdir(parents=True)

    print("unpacking the pinned tools", flush=True)
    unpack_tools(arch=arch, cache=work / "downloads", root=root)
    print("building the wheel set", flush=True)
    build_wheels(source=source, root=root, mtime=mtime, image=image)

    entry = root / TOOLS_ENTRY
    entry.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source / ENTRY_SOURCE, entry)
    entry.chmod(0o755)

    write_json(
        root / TOOLS_MANIFEST,
        {
            "package": name,
            "version": version,
            "commit": commit,
            "os": os_name,
            "arch": arch,
            "entry-point": TOOLS_ENTRY,
            "zephyr-sdk": ZEPHYR_SDK_VERSION,
            "zephyr-toolchain": ZEPHYR_TOOLCHAIN,
            "cmake": CMAKE_VERSION,
            "ninja": NINJA_VERSION,
            "gn": GN_REVISION,
        },
    )

    architecture = f"{os_name}-{arch}"
    # The family, with the platform said once: the concrete package name
    # is the two of them joined, and stating it twice would let them
    # disagree. `requires` is absent rather than empty — the tools are the
    # end of the chain and constrain nothing below them, which is a
    # different statement from "nothing in particular".
    meta = release_lines.json_bytes(
        release_lines.meta_document(
            name=TOOLS_FAMILY,
            version=version,
            architecture=architecture,
            requires=None,
            inputs=release_lines.inputs_sha256(
                "tools", commit, repository=repository, architecture=architecture
            ),
            contents=tools_contents(
                arch=arch,
                os_name=os_name,
                python=release_lines.packager_python(repository, commit),
                west=requirement_version(source / REQUIREMENTS_FILE, "west"),
            ),
        )
    )

    print("checking the host baseline", flush=True)
    assert_glibc_floor(root)
    print("packing", flush=True)
    return publish(root, output_dir, name=name, version=version, mtime=mtime, meta=meta)


# --------------------------------------------------------------------------
# The command line
# --------------------------------------------------------------------------


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--output-dir",
        type=Path,
        required=True,
        help="where the archive, its .sha256 sidecar and index.json are written",
    )
    parser.add_argument(
        "--work-dir",
        type=Path,
        help="scratch space (default: a temporary directory, removed afterwards)",
    )
    parser.add_argument(
        "--revision",
        default="HEAD",
        help="the commit to read this repository's inputs from (default: HEAD)",
    )
    parser.add_argument(
        "--repo",
        type=Path,
        default=REPO_ROOT,
        help="the checkout to read the revision from (default: this repository)",
    )
    parser.add_argument("kind", choices=("workspace", "tools"), help="which package to build")
    parser.add_argument(
        "--arch",
        default=os.uname().machine.replace("x86_64", "amd64").replace("aarch64", "arm64"),
        help="the tools package's architecture (default: this machine's)",
    )
    parser.add_argument("--os", dest="os_name", default="linux", help="the tools package's OS")
    parser.add_argument(
        "--packager-image",
        help=(
            "run the environment-specific steps in this image instead of the pinned "
            "packager (containers/build-environment-packager/); for publishing that "
            "image the first time and for trying a change to it"
        ),
    )
    parser.add_argument(
        "--version-suffix",
        help="append a PEP 440 local segment to the declared version, as in "
        "ci.<sha> for a per-commit build — a local version is the one shape "
        "a package host will not publish",
    )
    arguments = parser.parse_args(argv)

    # Asked for before anything is fetched or cloned: an unpinned packager
    # is a refusal, and a refusal is worth nothing after twenty minutes of
    # work.
    image = packager_image(arguments.packager_image)

    work = arguments.work_dir
    temporary = None
    if work is None:
        temporary = tempfile.TemporaryDirectory(prefix="mcuhome-env-package-")
        work = Path(temporary.name)
    work.mkdir(parents=True, exist_ok=True)

    try:
        if arguments.kind == "workspace":
            package = build_workspace_package(
                repository=arguments.repo,
                revision=arguments.revision,
                output_dir=arguments.output_dir,
                work=work,
                image=image,
                version_suffix=arguments.version_suffix,
            )
        else:
            package = build_tools_package(
                repository=arguments.repo,
                revision=arguments.revision,
                output_dir=arguments.output_dir,
                work=work,
                arch=arguments.arch,
                os_name=arguments.os_name,
                image=image,
                version_suffix=arguments.version_suffix,
            )
    finally:
        if temporary is not None:
            temporary.cleanup()

    print(f"{package.path.name}  {package.sha256}  {package.size} bytes")
    return 0


if __name__ == "__main__":  # pragma: no cover - the command line's entry point
    raise SystemExit(main(sys.argv[1:]))
